package ru.yandex.practicum.blog.dao;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;
import ru.yandex.practicum.blog.model.Comment;
import ru.yandex.practicum.blog.model.Post;

import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * PostgreSQL-based DAO.
 * We keep SQL here so service/controller stay DB-agnostic.
 */
@Repository
public class JdbcPostDao implements PostDao {
    private final JdbcTemplate jdbcTemplate;

    public JdbcPostDao(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public Post create(String title, String text, List<String> tags) {
        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(connection -> {
            PreparedStatement statement = connection.prepareStatement(
                    "INSERT INTO posts (title, text, likes_count, comments_count) VALUES (?, ?, 0, 0)",
                    new String[]{"id"}
            );
            statement.setString(1, title);
            statement.setString(2, text);
            return statement;
        }, keyHolder);

        Number generatedId = keyHolder.getKey();
        Long postId = generatedId == null ? null : generatedId.longValue();
        if (postId == null) {
            throw new IllegalStateException("Post id was not generated by database");
        }

        for (String tag : tags) {
            jdbcTemplate.update(
                    "INSERT INTO post_tags (post_id, tag) VALUES (?, ?)",
                    postId,
                    tag
            );
        }

        return findById(postId)
                .orElseThrow(() -> new IllegalStateException("Created post was not found by id " + postId));
    }

    @Override
    public Optional<Post> update(long id, String title, String text, List<String> tags) {
        int updatedRows = jdbcTemplate.update(
                "UPDATE posts SET title = ?, text = ? WHERE id = ?",
                title,
                text,
                id
        );
        if (updatedRows == 0) {
            return Optional.empty();
        }

        jdbcTemplate.update("DELETE FROM post_tags WHERE post_id = ?", id);
        for (String tag : tags) {
            jdbcTemplate.update(
                    "INSERT INTO post_tags (post_id, tag) VALUES (?, ?)",
                    id,
                    tag
            );
        }

        return findById(id);
    }

    @Override
    public boolean deleteById(long id) {
        int deletedRows = jdbcTemplate.update("DELETE FROM posts WHERE id = ?", id);
        return deletedRows > 0;
    }

    @Override
    public void saveImage(long id, byte[] imageBytes) {
        jdbcTemplate.update("DELETE FROM post_images WHERE post_id = ?", id);
        jdbcTemplate.update(
                "INSERT INTO post_images (post_id, image_data) VALUES (?, ?)",
                id,
                imageBytes
        );
    }

    @Override
    public Optional<Long> incrementLikes(long id) {
        int updatedRows = jdbcTemplate.update(
                "UPDATE posts SET likes_count = likes_count + 1 WHERE id = ?",
                id
        );
        if (updatedRows == 0) {
            return Optional.empty();
        }

        Long likesCount = jdbcTemplate.queryForObject(
                "SELECT likes_count FROM posts WHERE id = ?",
                Long.class,
                id
        );
        return Optional.ofNullable(likesCount);
    }

    @Override
    public Optional<Comment> findCommentById(long postId, long commentId) {
        List<Comment> comments = jdbcTemplate.query(
                "SELECT id, text, post_id FROM comments WHERE post_id = ? AND id = ?",
                (resultSet, ignoredRowNum) -> new Comment(
                        resultSet.getLong("id"),
                        resultSet.getString("text"),
                        resultSet.getLong("post_id")
                ),
                postId,
                commentId
        );
        if (comments.isEmpty()) {
            return Optional.empty();
        }
        return Optional.of(comments.getFirst());
    }

    @Override
    public Comment createComment(long postId, String text) {
        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(connection -> {
            PreparedStatement statement = connection.prepareStatement(
                    "INSERT INTO comments (text, post_id) VALUES (?, ?)",
                    new String[]{"id"}
            );
            statement.setString(1, text);
            statement.setLong(2, postId);
            return statement;
        }, keyHolder);

        Number generatedId = keyHolder.getKey();
        Long commentId = generatedId == null ? null : generatedId.longValue();
        if (commentId == null) {
            throw new IllegalStateException("Comment id was not generated by database");
        }

        jdbcTemplate.update(
                "UPDATE posts SET comments_count = comments_count + 1 WHERE id = ?",
                postId
        );

        return findCommentById(postId, commentId)
                .orElseThrow(() -> new IllegalStateException("Created comment was not found by id " + commentId));
    }

    @Override
    public Optional<Comment> updateComment(long postId, long commentId, String text) {
        int updatedRows = jdbcTemplate.update(
                "UPDATE comments SET text = ? WHERE post_id = ? AND id = ?",
                text,
                postId,
                commentId
        );
        if (updatedRows == 0) {
            return Optional.empty();
        }
        return findCommentById(postId, commentId);
    }

    @Override
    public boolean deleteComment(long postId, long commentId) {
        int deletedRows = jdbcTemplate.update(
                "DELETE FROM comments WHERE post_id = ? AND id = ?",
                postId,
                commentId
        );
        if (deletedRows == 0) {
            return false;
        }
        jdbcTemplate.update(
                "UPDATE posts SET comments_count = comments_count - 1 WHERE id = ?",
                postId
        );
        return true;
    }

    @Override
    public Optional<Post> findById(long id) {
        List<Post> posts = jdbcTemplate.query(
                "SELECT id, title, text, likes_count, comments_count FROM posts WHERE id = ?",
                (rs, rowNum) -> new Post(
                        rs.getLong("id"),
                        rs.getString("title"),
                        rs.getString("text"),
                        List.of(),
                        rs.getLong("likes_count"),
                        rs.getLong("comments_count")
                ),
                id
        );

        if (posts.isEmpty()) {
            return Optional.empty();
        }

        Post postWithoutTags = posts.getFirst();
        List<String> tags = jdbcTemplate.queryForList(
                "SELECT tag FROM post_tags WHERE post_id = ? ORDER BY tag",
                String.class,
                id
        );

        return Optional.of(new Post(
                postWithoutTags.id(),
                postWithoutTags.title(),
                postWithoutTags.text(),
                tags,
                postWithoutTags.likesCount(),
                postWithoutTags.commentsCount()
        ));
    }

    @Override
    public List<Post> findPage(String search, int pageNumber, int pageSize) {
        long offset = (long) (pageNumber - 1) * pageSize;
        SearchCriteria searchCriteria = parseSearch(search);
        List<Object> parameters = new ArrayList<>();
        StringBuilder sql = new StringBuilder(
                "SELECT p.id, p.title, p.text, p.likes_count, p.comments_count FROM posts p WHERE 1=1"
        );
        appendSearchConditions(sql, parameters, searchCriteria);
        sql.append(" ORDER BY p.id DESC LIMIT ? OFFSET ?");
        parameters.add(pageSize);
        parameters.add(offset);

        List<Post> postsWithoutTags = jdbcTemplate.query(
                sql.toString(),
                (resultSet, ignoredRowNum) -> new Post(
                        resultSet.getLong("id"),
                        resultSet.getString("title"),
                        resultSet.getString("text"),
                        List.of(),
                        resultSet.getLong("likes_count"),
                        resultSet.getLong("comments_count")
                ),
                parameters.toArray()
        );

        return attachTags(postsWithoutTags);
    }

    @Override
    public long countAll(String search) {
        SearchCriteria searchCriteria = parseSearch(search);
        List<Object> parameters = new ArrayList<>();
        StringBuilder sql = new StringBuilder("SELECT COUNT(*) FROM posts p WHERE 1=1");
        appendSearchConditions(sql, parameters, searchCriteria);

        Long count = jdbcTemplate.queryForObject(
                sql.toString(),
                Long.class,
                parameters.toArray()
        );
        return count == null ? 0L : count;
    }

    @Override
    public Optional<byte[]> findImageByPostId(long id) {
        List<byte[]> images = jdbcTemplate.query(
                "SELECT image_data FROM post_images WHERE post_id = ?",
                (resultSet, ignoredRowNum) -> resultSet.getBytes("image_data"),
                id
        );

        if (images.isEmpty()) {
            return Optional.empty();
        }

        return Optional.ofNullable(images.getFirst());
    }

    @Override
    public List<Comment> findCommentsByPostId(long postId) {
        return jdbcTemplate.query(
                "SELECT id, text, post_id FROM comments WHERE post_id = ? ORDER BY id",
                (resultSet, ignoredRowNum) -> new Comment(
                        resultSet.getLong("id"),
                        resultSet.getString("text"),
                        resultSet.getLong("post_id")
                ),
                postId
        );
    }

    /**
     * Batched tag loading avoids "N+1 queries" when returning feed pages.
     */
    private List<Post> attachTags(List<Post> postsWithoutTags) {
        if (postsWithoutTags.isEmpty()) {
            return List.of();
        }

        List<Long> postIds = postsWithoutTags.stream()
                .map(Post::id)
                .toList();
        String placeholders = postIds.stream()
                .map(id -> "?")
                .collect(Collectors.joining(","));

        List<TagRow> tagRows = jdbcTemplate.query(
                "SELECT post_id, tag FROM post_tags WHERE post_id IN (" + placeholders + ") ORDER BY post_id, tag",
                (rs, rowNum) -> new TagRow(
                        rs.getLong("post_id"),
                        rs.getString("tag")
                ),
                postIds.toArray()
        );

        Map<Long, List<String>> tagsByPostId = new HashMap<>();
        for (TagRow tagRow : tagRows) {
            tagsByPostId.computeIfAbsent(tagRow.postId(), ignored -> new java.util.ArrayList<>())
                    .add(tagRow.tag());
        }

        return postsWithoutTags.stream()
                .map(post -> new Post(
                        post.id(),
                        post.title(),
                        post.text(),
                        tagsByPostId.getOrDefault(post.id(), List.of()),
                        post.likesCount(),
                        post.commentsCount()
                ))
                .toList();
    }

    private record TagRow(long postId, String tag) {
    }

    private void appendSearchConditions(StringBuilder sql, List<Object> parameters, SearchCriteria searchCriteria) {
        if (searchCriteria.titleSearch() != null) {
            sql.append(" AND LOWER(p.title) LIKE ?");
            parameters.add(searchCriteria.titleSearch());
        }

        for (int i = 0; i < searchCriteria.requiredTags().size(); i++) {
            sql.append(" AND EXISTS (")
                    .append("SELECT 1 FROM post_tags pt").append(i)
                    .append(" WHERE pt").append(i).append(".post_id = p.id")
                    .append(" AND LOWER(pt").append(i).append(".tag) = ?")
                    .append(")");
            parameters.add(searchCriteria.requiredTags().get(i));
        }
    }

    private SearchCriteria parseSearch(String search) {
        if (search == null || search.isBlank()) {
            return new SearchCriteria(null, List.of());
        }

        List<String> titleTerms = new ArrayList<>();
        List<String> tagTerms = new ArrayList<>();
        for (String word : search.trim().split("\\s+")) {
            if (word.isBlank()) {
                continue;
            }

            if (word.startsWith("#")) {
                String tag = word.substring(1).trim().toLowerCase();
                if (!tag.isBlank()) {
                    tagTerms.add(tag);
                }
                continue;
            }

            titleTerms.add(word);
        }

        String titleSearch = titleTerms.isEmpty()
                ? null
                : "%" + String.join(" ", titleTerms).toLowerCase() + "%";

        return new SearchCriteria(titleSearch, tagTerms.stream().distinct().toList());
    }

    private record SearchCriteria(String titleSearch, List<String> requiredTags) {
    }
}
